package pk.models;
// Generated 21 mars 2022 05:55:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carte generated by hbm2java
 */
@Entity
@Table(name="CARTE"
    ,schema="VISA"
)
public class Carte  implements java.io.Serializable {


     private long nocart;
     private String datevalid;
     private Short crypto;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Carte() {
    }

	
    public Carte(long nocart) {
        this.nocart = nocart;
    }
    public Carte(long nocart, String datevalid, Short crypto, Set<Transaction> transactions) {
       this.nocart = nocart;
       this.datevalid = datevalid;
       this.crypto = crypto;
       this.transactions = transactions;
    }
   
     @Id 

    
    @Column(name="NOCART", unique=true, nullable=false, precision=16, scale=0)
    public long getNocart() {
        return this.nocart;
    }
    
    public void setNocart(long nocart) {
        this.nocart = nocart;
    }

    
    @Column(name="DATEVALID", length=5)
    public String getDatevalid() {
        return this.datevalid;
    }
    
    public void setDatevalid(String datevalid) {
        this.datevalid = datevalid;
    }

    
    @Column(name="CRYPTO", precision=3, scale=0)
    public Short getCrypto() {
        return this.crypto;
    }
    
    public void setCrypto(Short crypto) {
        this.crypto = crypto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="carte")
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


