package pk.models;
// Generated 21 mars 2022 05:55:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name="TRANSACTION"
    ,schema="VISA"
)
@SequenceGenerator(name = "seq_tx",sequenceName = "seq_tx")
public class Transaction  implements java.io.Serializable {


     private int idtx;
     private Carte carte;
     private Date datetx;
     private float mnttx;

    public Transaction() {
    }

	
    public Transaction(int idtx) {
        this.idtx = idtx;
    }
    public Transaction(int idtx, Carte carte, Date datetx, float mnttx) {
       this.idtx = idtx;
       this.carte = carte;
       this.datetx = datetx;
       this.mnttx = mnttx;
    }
   
     @Id 

    @GeneratedValue(generator = "seq_tx",strategy = GenerationType.SEQUENCE)
    @Column(name="IDTX", unique=true, nullable=false, precision=8, scale=0)
    public int getIdtx() {
        return this.idtx;
    }
    
    public void setIdtx(int idtx) {
        this.idtx = idtx;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NOCART")
    public Carte getCarte() {
        return this.carte;
    }
    
    public void setCarte(Carte carte) {
        this.carte = carte;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATETX", length=7)
    public Date getDatetx() {
        return this.datetx;
    }
    
    public void setDatetx(Date datetx) {
        this.datetx = datetx;
    }

    
    @Column(name="MNTTX", precision=10)
    public float getMnttx() {
        return this.mnttx;
    }
    
    public void setMnttx(float mnttx) {
        this.mnttx = mnttx;
    }




}


